### ISSUE TITLE
Issues/error with some examples

### ISSUE THREAD

**Issue by bvernoux** [dlharmon/pyopenems#7]
I have built pyopenems with Ubuntu 18.04 LTS 64bits like described in https://github.com/dlharmon/pyopenems/issues/6
But I have some issues with some examples (I doubt it is related to my build)
- pyopenems/examples/lpf_6.py
```
Traceback (most recent call last):
  File "lpf_6.py", line 39, in <module>
    box_width = 1.8*mm)
  File "/home/hydra/pyopenems/examples/openems/lpf.py", line 25, in generate
    l2 = l1.duplicate("line_p2").mirror('x')
AttributeError: 'Box' object has no attribute 'duplicate'
```
The same for
- pyopenems/examples/lpf_13.py 
```
Traceback (most recent call last):
  File "lpf_13.py", line 40, in <module>
    box_width = 1.8*mm)
  File "/home/hydra/pyopenems/examples/openems/lpf.py", line 25, in generate
    l2 = l1.duplicate("line_p2").mirror('x')
AttributeError: 'Box' object has no attribute 'duplicate'
```

**Comment by dlharmon** [comment]
I removed the old low pass filters and plan to replace them with one derived from LPF_DGS_bowtie.py at some point. I'll leave this issue open to track that. Thanks for reporting.

**Comment by bvernoux** [comment]
Thanks for your very fast fixes pyopenems is really amazing and your examples very interesting !!
